# Schema for the configuration files of the tmgmt_smartling_log_settings module.

tmgmt_smartling_log_settings.settings:
  type: config_object
  label: 'Smartling log settings'
  mapping:
    severity_mapping:
      type: string
      label: 'Severity mapping'
