tmgmt_extension_suit.settings:
  type: config_entity
  label: 'TMGMT settings'
  mapping:
    do_track_changes:
      type: boolean
      label: 'Track if "in translation" entity was chaged.'

action.configuration.tmgmt_extension_suit_cancel_job_action:
  type: action_configuration_default
  label: 'Cancel Job'

action.configuration.tmgmt_extension_suit_delete_job_action:
  type: action_configuration_default
  label: 'Delete Job'

action.configuration.tmgmt_extension_suit_download_job_action:
  type: action_configuration_default
  label: 'Download Translation'

action.configuration.tmgmt_extension_suit_request_translation_job_action:
  type: action_configuration_default
  label: 'Request Translation'

action.configuration.tmgmt_extension_suit_clear_job_items_data_action:
  type: action_configuration_default
  label: 'Clear JobItem cache (data property)'
